// Mock data for the creator dashboard. Replace with live data once the
// brand-side gig publishing pipeline is wired up.

export const CATEGORIES = [
  "Social & Communication",
  "Finance & Commerce",
  "Entertainment & Media",
  "Health & Fitness",
  "Education & Learning",
  "Travel & Local",
  "Lifestyle & Utilities",
  "Photo & Video",
  "Home & Family",
  "Fashion & Beauty",
  "Food & Drink",
  "Other",
];

export const mockOpenGigs = [
  {
    id: "g1",
    title: "Skincare unboxing video",
    brand: "Acme Skincare",
    category: "Fashion & Beauty",
    payout: 80,
    payoutUnit: "post",
    deadline: "5 days",
    cover: "from-rose-200 to-amber-100",
    tag: "UGC Ads",
  },
  {
    id: "g2",
    title: "Morning coffee ad",
    brand: "Brew Co.",
    category: "Food & Drink",
    payout: 120,
    payoutUnit: "post",
    deadline: "2 days",
    cover: "from-amber-200 to-orange-100",
    tag: "High Volume UGC",
  },
  {
    id: "g3",
    title: "FitCheck UGC creator",
    brand: "FitCheck",
    category: "Health & Fitness",
    payout: 4,
    payoutUnit: "1k views",
    deadline: "Rolling",
    cover: "from-lime-200 to-emerald-100",
    tag: "High Volume UGC",
  },
  {
    id: "g4",
    title: "Language learning testimonial",
    brand: "Bueno Spanish",
    category: "Education & Learning",
    payout: 500,
    payoutUnit: "month",
    deadline: "Rolling",
    cover: "from-sky-200 to-indigo-100",
    tag: "High Volume UGC",
  },
  {
    id: "g5",
    title: "Project Bullhorn UGC campaign",
    brand: "Project Bullhorn",
    category: "Entertainment & Media",
    payout: 500,
    payoutUnit: "month",
    deadline: "7 days",
    cover: "from-violet-200 to-fuchsia-100",
    tag: "High Volume UGC",
  },
  {
    id: "g6",
    title: "Granola weekly creator",
    brand: "Granola",
    category: "Food & Drink",
    payout: 150,
    payoutUnit: "week",
    deadline: "Rolling",
    cover: "from-yellow-200 to-amber-100",
    tag: "UGC Ads",
  },
  {
    id: "g7",
    title: "Oddpool creator campaign",
    brand: "Oddpool",
    category: "Lifestyle & Utilities",
    payout: 1750,
    payoutUnit: "month",
    deadline: "Rolling",
    cover: "from-slate-200 to-zinc-100",
    tag: "High Volume UGC",
  },
  {
    id: "g8",
    title: "Survivor & Love Island UGC",
    brand: "Ponder Labs",
    category: "Entertainment & Media",
    payout: 300,
    payoutUnit: "month",
    deadline: "Rolling",
    cover: "from-orange-200 to-rose-100",
    tag: "High Volume UGC",
  },
  {
    id: "g9",
    title: "Motiv step challenge ad",
    brand: "Motiv",
    category: "Health & Fitness",
    payout: 30,
    payoutUnit: "post",
    deadline: "10 days",
    cover: "from-teal-200 to-cyan-100",
    tag: "UGC Ads",
  },
];

export const mockApplications = [
  {
    id: "ap1",
    gigTitle: "Skincare unboxing video",
    brand: "Acme Skincare",
    status: "pending",
    appliedAt: "2 days ago",
  },
  {
    id: "ap2",
    gigTitle: "Morning coffee ad",
    brand: "Brew Co.",
    status: "shortlisted",
    appliedAt: "5 days ago",
  },
];

export const APPLICATION_STATUS = {
  pending: { label: "Pending review", classes: "bg-slate-100 text-slate-600 border-slate-200" },
  shortlisted: { label: "Shortlisted", classes: "bg-sky-50 text-sky-700 border-sky-200" },
  accepted: { label: "Accepted", classes: "bg-emerald-50 text-emerald-700 border-emerald-200" },
  declined: { label: "Declined", classes: "bg-rose-50 text-rose-700 border-rose-200" },
};
